pipeline:
  build:
    image: cypress/included:6.1.0
    commands:
      - npm install
      - npm run test:e2e
  publish:
    image: plugins/docker
    repo: drone/node-demo
    secrets: [ docker_username, docker_password ]
    dry_run: true # remove this to publish
